spring:
    resources:
        static-locations: file:${ftp.home-dir}
    mvc:
        static-path-pattern: /res/**
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: "jdbc:mariadb://localhost:3306/venom?characterEncoding=UTF-8&serverTimezone=UTC"
        username: root
        password: 1234qwer
        hikari:
            auto-commit: false
            connection-test-query: SELECT 1
            minimum-idle: 10
            maximum-pool-size: 30
            transaction-isolation: TRANSACTION_READ_UNCOMMITTED
            pool-name: pool-venom
server:
    host: localhost # This should be your server's real IP
    port:
        http: 8080
        ftp: 21

logging:
    level:
        root: info
        com.zapple: debug
    file:
        name: spring.log
ftp:
    passive-ports:
    max-logins: 0
    max-threads: 0
    username: admin
    password: admin
    home-dir: res/
